-- Portfolio content tables for oracle_instance.
--
-- Run this by hand (psql, a GUI client, etc.) connected to the same
-- Postgres database Django uses, with your session's search_path pointing
-- at whatever schema DB_SCHEMA is set to (see oracle-backend/backend/.env
-- and the repo-root .env used by docker-compose) - same convention as the
-- existing "mortgage" and "topics" tables. Table names below are NOT
-- schema-qualified on purpose, exactly like those two.
--
-- Run portfolio_seed.sql right after this to populate real starter content.
--
-- All the tables here are prefixed "portfolio_" to keep them obviously
-- grouped and separate from other apps' tables sharing the same schema.

CREATE TABLE portfolio_profile (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(150) NOT NULL,
    role_title      VARCHAR(200) NOT NULL,
    hero_heading    VARCHAR(200) NOT NULL,
    hero_bio        TEXT NOT NULL,
    about_heading   VARCHAR(200) NOT NULL DEFAULT 'About Me',
    about_bio       TEXT NOT NULL,
    hero_image      VARCHAR(255),
    about_image     VARCHAR(255),
    email           VARCHAR(255),
    location        VARCHAR(150),
    resume_url      VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Singleton table: exactly one row. Django Admin (ProfileAdmin) blocks
-- adding a second row; nothing at the database level enforces it.

CREATE TABLE portfolio_stat (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label           VARCHAR(100) NOT NULL,
    value           INTEGER NOT NULL,
    suffix          VARCHAR(10) NOT NULL DEFAULT '+',
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- About-page counters, e.g. "20+ Projects". Sorted by display_order.

CREATE TABLE portfolio_skill (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    category        VARCHAR(100),
    is_featured     BOOLEAN NOT NULL DEFAULT FALSE,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- is_featured = TRUE -> shown as a tech badge on the home page hero.
-- All skills (featured or not) show on the About page.

CREATE TABLE portfolio_experience (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position        VARCHAR(200) NOT NULL,
    company         VARCHAR(200) NOT NULL,
    company_url     VARCHAR(500),
    location        VARCHAR(150),
    start_date      DATE NOT NULL,
    end_date        DATE,                 -- NULL = "Present"
    description     TEXT NOT NULL,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE portfolio_project (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200) NOT NULL,
    slug            VARCHAR(220) NOT NULL UNIQUE,
    description     TEXT NOT NULL,
    image           VARCHAR(255),
    project_url     VARCHAR(500),
    github_url      VARCHAR(500),
    app_store_url   VARCHAR(500),
    is_internal     BOOLEAN NOT NULL DEFAULT FALSE,
    is_in_progress  BOOLEAN NOT NULL DEFAULT FALSE,
    display_order   INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE portfolio_tag (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    slug            VARCHAR(110) NOT NULL UNIQUE
);
-- Shared tag vocabulary (e.g. "Next.js", "Python") used to filter projects.

CREATE TABLE portfolio_project_tag (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT NOT NULL REFERENCES portfolio_project(id) ON DELETE CASCADE,
    tag_id          BIGINT NOT NULL REFERENCES portfolio_tag(id) ON DELETE CASCADE,
    UNIQUE (project_id, tag_id)
);
-- Many-to-many join between projects and tags. Managed in Django Admin as
-- an inline on each Project (not a separate screen).

CREATE TABLE portfolio_social_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform        VARCHAR(50) NOT NULL,   -- 'github' | 'linkedin' | 'email' | ...
    label           VARCHAR(100) NOT NULL,
    url             VARCHAR(500) NOT NULL,
    display_order   INTEGER NOT NULL DEFAULT 0
);
